//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Shairport4w.rc
//
#define IDD_ABOUTBOX                    100
#define ID_MENU_ENTRY_ID_ONLINE_UPDATE  103
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDS_TRACK_LABEL                 129
#define IDS_TRAY_ACK                    130
#define IDS_ALBUM_LABEL                 131
#define IDS_ARTIST_LABEL                132
#define IDS_NOW_PLAYING                 133
#define IDS_BUFFERING                   134
#define IDS_SYSTEM_DEFAULT              135
#define IDS_INSTALL_BONJOUR             136
#define IDS_STATUS_CONNECTED            138
#define IDS_UNINSTALL                   140
#define IDS_UNINSTALL_ERROR             141
#define IDS_ERR_MULTIPLE_INSTANCES      142
#define IDS_UNINSTALL_SUCCESS           143
#define IDS_UNINSTALL_SUCCESS_REBOOT    144
#define IDS_ONLINE_UPDATE               145
#define IDS_UPDATE_ERROR_FMT            146
#define IDS_DOWNLOAD_ERROR_FMT          147
#define IDS_NEW_VERSION_AVAILABLE       148
#define IDS_UPDATE_NOT_SIGNED           149
#define IDS_FILE_NOT_SIGNED             150
#define IDS_NO_NEW_VERSION              151
#define IDS_CANCEL                      152
#define IDS_LOAD_UPDATE                 153
#define IDR_MENU1                       201
#define IDR_TRAY                        201
#define IDD_EXT_OPTS                    203
#define IDD_CHANGEUSER                  204
#define IDR_MAINMENU                    207
#define IDB_WMC                         208
#define IDR_TRAY1                       208
#define IDI_ICON1                       210
#define IDI_ICON3                       214
#define IDB_PNG1                        220
#define IDB_PLAY                        221
#define IDB_PAUSE                       222
#define IDB_PLAY_DISABLED               223
#define IDB_PLAY_PRESSED                224
#define IDB_FFW                         225
#define IDB_FFW_DISABLED                226
#define IDB_FFW_PRESSED                 227
#define IDB_PAUSE_DISABLED              229
#define IDB_PAUSE_PRESSED               230
#define IDB_REW                         231
#define IDB_REW_DISABLED                232
#define IDB_REW_PRESSED                 233
#define IDB_SKIP_PREV                   237
#define IDB_SKIP_PREV_DISABLED          238
#define IDB_SKIP_PREV_PRESSED           239
#define IDB_SKIP_NEXT                   240
#define IDB_SKIP_NEXT_DISABLED          241
#define IDB_SKIP_NEXT_PRESSED           242
#define IDB_PUSH_PIN_PRESSED            243
#define IDB_PNG3                        244
#define IDB_PUSH_PIN_RELEASED           244
#define IDB_PNG2                        245
#define IDB_PROGRESS_SHADOW             245
#define IDB_PNG4                        246
#define IDB_AD_SHADOW                   246
#define IDB_PNG5                        247
#define IDB_ART_SHADOW                  247
#define IDB_MUTE                        248
#define IDB_MUTE_PRESSED                249
#define IDB_UPDATE_16                   252
#define IDD_PROGRESS                    253
#define IDD_LIC_DIALOG                  254
#define IDD_LIC_DIALOG1                 255
#define IDC_APNAME                      1000
#define IDC_CHANGENAME                  1001
#define IDC_CHECK1                      1002
#define IDC_START_MINIMIZED             1002
#define IDC_LOG_TO_FILE                 1002
#define IDC_UPDATE                      1004
#define IDC_EXTENDED_OPTIONS            1005
#define IDC_AUTOSTART                   1006
#define IDC_CHECK2                      1007
#define IDC_TRAY                        1007
#define IDC_NO_META_INFO                1007
#define IDC_EDIT1                       1008
#define IDC_PASSWORD                    1008
#define IDC_NAME                        1008
#define IDC_NO_META_INFO2               1008
#define IDC_NO_NEDIA_CONTROLS           1008
#define IDC_EDIT                        1008
#define IDC_DNSSD_DLL                   1009
#define IDC_PASS                        1009
#define IDC_INFOPANEL                   1009
#define IDC_DNSSD_EXE                   1010
#define IDC_VERIFYPASS                  1010
#define IDC_COMBO1                      1012
#define IDC_PROXY                       1012
#define IDC_SOUNDCARD                   1013
#define IDC_BUFFERING                   1016
#define IDC_STATIC_BUFFERING            1017
#define IDC_STATIC_PANEL                1018
#define IDC_INFO_BMP                    1019
#define IDC_STATIC_TIME_INFO            1022
#define IDC_STATIC_ARTIST               1023
#define IDC_PUSH_PIN                    1024
#define IDC_STATIC_TIME_INFO2           1025
#define IDC_STATIC_TIME_INFO_CURRENT    1025
#define IDC_STATIC_TRACK                1026
#define IDC_STATIC_ALBUM                1027
#define IDC_TIME_BAR                    1028
#define IDC_CONTROL_PANEL               1029
#define IDC_MM_SKIP_PREV                1030
#define IDC_STATIC_ICONS8               1030
#define IDC_MM_REW                      1031
#define IDC_STATIC_ICONS9               1031
#define IDC_STATIC_SHAIR_LNK            1031
#define IDC_MM_PAUSE                    1032
#define IDC_STATIC_VERSION              1032
#define IDC_MM_PLAY                     1033
#define IDC_MM_FFW                      1034
#define IDC_MM_SKIP_NEXT                1035
#define IDC_MM_SHUFFLE                  1036
#define IDC_MM_SKIP_PREV2               1036
#define IDC_MM_MUTE                     1036
#define IDC_MM_MUTE_ON                  1037
#define IDC_STATUS_PANEL                1037
#define IDC_MM_MUTE_OFF                 1038
#define IDC_CONTROL_PANEL3              1038
#define IDC_STATIC_STATUS               1039
#define IDC_STATIC_SPR_ICON             1040
#define IDC_STATIC_SPR1                 1041
#define IDC_STATIC_SPR2                 1042
#define IDC_STATIC_ICONS8_LNK           1043
#define IDC_STATIC_FRAME                1044
#define IDC_CHECK4                      1046
#define IDC_STATIC_WAVEOUT              1047
#define IDC_PROGRESS1                   1048
#define IDC_PROGRESS                    1048
#define IDC_STATIC_INFO                 1049
#define IDC_STATIC_1                    1050
#define IDC_STATIC_2                    1051
#define IDC_BUTTON1                     1052
#define IDC_STATIC_BRAND_ICON           1053
#define ID__SHOW                        32775
#define IDC_SHOW                        32776
#define ID_PIN                          32783
#define ID_EDIT_TRAYTRACKINFO           32784
#define ID_E                            32785
#define ID_REFRESH                      32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        259
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
